let ALL=[],statusChart=null,projectChart=null;document.addEventListener("DOMContentLoaded",init);
async function init(){bind();const r=await fetch("sae_data.json?ts="+Date.now());ALL=(await r.json()).map(norm);filters();times();render(ALL)}
function bind(){["projectFilter","buildFilter","picFilter","stageFilter","yearFilter","monthFilter","weekFilter","fromDate","toDate"].forEach(id=>document.getElementById(id).addEventListener("change",apply));document.getElementById("searchInput").addEventListener("input",apply);document.getElementById("resetButton").addEventListener("click",()=>{["projectFilter","buildFilter","picFilter","stageFilter","yearFilter","monthFilter","weekFilter","fromDate","toDate"].forEach(id=>document.getElementById(id).value="");document.getElementById("searchInput").value="";render(ALL)});document.getElementById("exportButton").addEventListener("click",exportCSV);document.getElementById("importButton").addEventListener("click",()=>alert("Import will connect to SAE later."));document.getElementById("langEn").onclick=()=>lang("en");document.getElementById("langZh").onclick=()=>lang("zh")}
function norm(x){const g=gap(x["NBD"]),p=stage(x);return{...x,_gap:g,_stage:p.stage,_action:p.action,_priority:priority(g,x["Dispatched date"])}}
function gap(v){const d=parse(v);if(!d)return null;const t=new Date();t.setHours(0,0,0,0);return Math.floor((t-d)/86400000)}
function priority(g,d){if(has(d))return{text:"● Dispatched",cls:"p-green"};if(g===null)return{text:"● No NBD",cls:"p-gray"};if(g>0)return{text:"● Overdue",cls:"p-red"};if(g>=-3)return{text:"● Due ≤3d",cls:"p-orange"};if(g>=-7)return{text:"● Due ≤7d",cls:"p-yellow"};return{text:"● Upcoming",cls:"p-green"}}
function stage(x){if(txt(x["Type"]).toLowerCase()==="inhouse")return{stage:"Project / Inhouse Follow-up",action:"Check execution progress vs NBD"};if(!has(x["FIH PO Number"]))return{stage:"FIH PO Pending",action:"Follow up FIH PO number"};if(has(x["Target date"])&&!has(x["Released"]))return{stage:"FIH PO Release Pending",action:"Follow up FIH PO release"};if(!has(x["Vendor ETD"]))return{stage:"Vendor ETD Pending",action:"Confirm Vendor ETD"};if(!has(x["AWB Bill"]))return{stage:"AWB Pending",action:"Get AWB / shipment confirmation"};if(!has(x["BFIH Actual ETA"])&&!has(x["BFIH site arrive"]))return{stage:"BFIH Arrival Pending",action:"Track shipment / confirm BFIH arrival"};return{stage:"Dispatch Pending",action:"Push dispatch to customer"}}
function filters(){fill("projectFilter",ALL.map(x=>x["Project"]));fill("buildFilter",ALL.map(x=>x["Build"]));fill("picFilter",ALL.map(x=>x["PIC"]));fill("stageFilter",ALL.map(x=>x._stage))}
function times(){[...new Set(ALL.map(x=>parse(x["NBD"])).filter(Boolean).map(d=>d.getFullYear()))].forEach(y=>document.getElementById("yearFilter").insertAdjacentHTML("beforeend",`<option value="${y}">${y}</option>`));["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"].forEach((n,i)=>document.getElementById("monthFilter").insertAdjacentHTML("beforeend",`<option value="${i+1}">${n}</option>`));for(let i=1;i<=53;i++)document.getElementById("weekFilter").insertAdjacentHTML("beforeend",`<option value="${i}">W${i}</option>`)}
function fill(id,a){const e=document.getElementById(id);[...new Set(a.filter(has).map(txt))].sort().forEach(v=>e.insertAdjacentHTML("beforeend",`<option value="${v}">${v}</option>`))}
function apply(){const p=val("projectFilter"),b=val("buildFilter"),pc=val("picFilter"),st=val("stageFilter"),y=+val("yearFilter"),m=+val("monthFilter"),w=+val("weekFilter"),f=val("fromDate"),t=val("toDate"),q=document.getElementById("searchInput").value.toLowerCase();render(ALL.filter(x=>{if(p&&txt(x["Project"])!==p)return false;if(b&&txt(x["Build"])!==b)return false;if(pc&&txt(x["PIC"])!==pc)return false;if(st&&x._stage!==st)return false;const d=parse(x["NBD"]);if(y&&(!d||d.getFullYear()!==y))return false;if(m&&(!d||d.getMonth()+1!==m))return false;if(w&&(!d||isoWeek(d)!==w))return false;if(f&&(!d||d<new Date(f+"T00:00:00")))return false;if(t&&(!d||d>new Date(t+"T23:59:59")))return false;if(q&&!([x["Project"],x["Build"],x["Machine/Equipment name"],x["Spec"],x["PIC"],x["Vendor"]].map(txt).join(" ").toLowerCase().includes(q)))return false;return true}))}
function render(d){const total=d.length,o=d.filter(x=>x._gap!==null&&x._gap>0&&!has(x["Dispatched date"])).length,d3=d.filter(x=>x._gap<=0&&x._gap>=-3).length,d7=d.filter(x=>x._gap<=-4&&x._gap>=-7).length,dis=d.filter(x=>has(x["Dispatched date"])).length;set("totalCount",total);set("overdueCount",o);set("due3Count",d3);set("due7Count",d7);set("dispatchedCount",dis);set("totalPercent",total?"100%":"0%");set("overduePercent",pct(o,total));set("due3Percent",pct(d3,total));set("due7Percent",pct(d7,total));set("dispatchedPercent",pct(dis,total));pending(d);donut(d);bar(d)}
function pending(d){const rows=d.filter(x=>!has(x["Dispatched date"])).sort((a,b)=>(b._gap??-999999)-(a._gap??-999999));set("pendingCount",rows.length+" items");document.getElementById("pendingBody").innerHTML=rows.map(x=>`<tr><td><span class="priority ${x._priority.cls}">${x._priority.text}</span></td><td>${txt(x["Project"])}<br><b>${txt(x["Build"])}</b></td><td>${txt(x["Machine/Equipment name"])}</td><td>${date(x["NBD"])}</td><td>${date(x["BFIH site arrive"])}</td><td class="${gapcls(x._gap)}">${x._gap===null?"":x._gap>0?"+"+x._gap:x._gap}</td><td class="stage">${x._stage}</td><td>${x._action}</td></tr>`).join("")}
function donut(d){if(typeof Chart==="undefined")return;const c={};d.forEach(x=>{const s=has(x["Overall status"])?txt(x["Overall status"]):"No Status";c[s]=(c[s]||0)+1});if(statusChart)statusChart.destroy();statusChart=new Chart(document.getElementById("statusChart"),{type:"doughnut",data:{labels:Object.keys(c),datasets:[{data:Object.values(c),backgroundColor:["#1769e0","#26a34a","#f58213","#ef2b1f","#eeb308"]}]},options:{responsive:true,maintainAspectRatio:false,cutout:"58%"}})}
function bar(d){if(typeof Chart==="undefined")return;const g={};d.forEach(x=>{const k=txt(x["Project"])+" "+txt(x["Build"]);g[k]=(g[k]||0)+1});if(projectChart)projectChart.destroy();projectChart=new Chart(document.getElementById("projectChart"),{type:"bar",data:{labels:Object.keys(g),datasets:[{label:"Items",data:Object.values(g),backgroundColor:"#1769e0"}]},options:{responsive:true,maintainAspectRatio:false,indexAxis:"y"}})}
function exportCSV(){const rows=ALL.map(x=>[x["Project"],x["Build"],x["Machine/Equipment name"],x["NBD"],x._gap,x._stage,x._action]);const csv=[["Project","Build","Machine","NBD","CP Gap","Stage","Action"],...rows].map(r=>r.join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="SAE_dashboard.csv";a.click()}
function lang(l){document.getElementById("langEn").classList.toggle("active",l==="en");document.getElementById("langZh").classList.toggle("active",l==="zh");document.getElementById("exportButton").textContent=l==="zh"?"导出":"Export";document.getElementById("importButton").textContent=l==="zh"?"导入":"Import"}
function isoWeek(date){const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()));const day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()+4-day);const y=new Date(Date.UTC(d.getUTCFullYear(),0,1));return Math.ceil((((d-y)/86400000)+1)/7)}
function parse(v){const s=txt(v);if(/^\d{4}-\d{2}-\d{2}$/.test(s)){const[y,m,d]=s.split("-").map(Number);return new Date(y,m-1,d)}return null}function date(v){const d=parse(v);return d?`${String(d.getMonth()+1).padStart(2,"0")}/${String(d.getDate()).padStart(2,"0")}`:txt(v)}function has(v){const s=txt(v);return s&&s!=="-"&&s.toUpperCase()!=="TBC"}function txt(v){return v==null?"":String(v).trim()}function val(id){return document.getElementById(id).value}function set(id,v){document.getElementById(id).textContent=v}function pct(n,t){return t?Math.round(n/t*100)+"%":"0%"}function gapcls(v){return v===null?"":v>0?"gap-overdue":v>=-7?"gap-near":"gap-safe"}