let ALL=[],statusChart=null,currentData=[];document.addEventListener("DOMContentLoaded",init);
async function init(){bind();try{const r=await fetch("sae_data.json?ts="+Date.now());ALL=(await r.json()).map(norm);times();render(ALL)}catch(e){console.error(e)}}
function bind(){["yearFilter","monthFilter","weekFilter","fromDate","toDate"].forEach(id=>document.getElementById(id).addEventListener("change",apply));document.getElementById("exportButton").onclick=exportCSV;document.getElementById("importButton").onclick=()=>alert("Import module will use SAE sheet data after the web is completed.");document.getElementById("langEn").onclick=()=>lang("en");document.getElementById("langZh").onclick=()=>lang("zh");document.querySelectorAll('.nav-link').forEach(a=>a.onclick=e=>{e.preventDefault();document.querySelectorAll('.nav-link').forEach(x=>x.classList.remove('active'));a.classList.add('active');if(a.dataset.page==='manufacture')alert('Manufacture data source will be connected later.');if(a.dataset.page==='import')render(ALL)})}
function norm(x){const g=gap(x["NBD"]),p=stage(x);return{...x,_gap:g,_stage:p.stage,_action:p.action,_priority:priority(g,x["Dispatched date"])}}
function gap(v){const d=parse(v);if(!d)return null;const t=new Date();t.setHours(0,0,0,0);return Math.floor((t-d)/86400000)}
function priority(g,d){if(has(d))return{text:"● Dispatched",cls:"p-green"};if(g===null)return{text:"● No NBD",cls:"p-gray"};if(g>0)return{text:"● Overdue",cls:"p-red"};if(g>=-3)return{text:"● Due ≤3d",cls:"p-orange"};if(g>=-7)return{text:"● Due ≤7d",cls:"p-yellow"};return{text:"● Upcoming",cls:"p-green"}}
function stage(x){if(txt(x["Type"]).toLowerCase()==="inhouse")return{stage:"Project / Inhouse Follow-up",action:"Check execution progress vs NBD"};if(!has(x["FIH PO Number"]))return{stage:"FIH PO Pending",action:"Follow up FIH PO number"};if(has(x["Target date"])&&!has(x["Released"]))return{stage:"FIH PO Release Pending",action:"Follow up FIH PO release"};if(!has(x["Vendor ETD"]))return{stage:"Vendor ETD Pending",action:"Confirm Vendor ETD"};if(!has(x["AWB Bill"]))return{stage:"AWB Pending",action:"Get AWB / shipment confirmation"};if(!has(x["BFIH Actual ETA"])&&!has(x["BFIH site arrive"]))return{stage:"BFIH Arrival Pending",action:"Track shipment / confirm BFIH arrival"};if(!has(x["Dispatched date"]))return{stage:"Dispatch Pending",action:"Push dispatch to customer"};return{stage:"Completed",action:"-"}}
function times(){[...new Set(ALL.map(x=>parse(x["NBD"])).filter(Boolean).map(d=>d.getFullYear()))].sort().forEach(y=>yearFilter.insertAdjacentHTML('beforeend',`<option value="${y}">${y}</option>`));["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"].forEach((n,i)=>monthFilter.insertAdjacentHTML('beforeend',`<option value="${i+1}">${n}</option>`));for(let i=1;i<=53;i++)weekFilter.insertAdjacentHTML('beforeend',`<option value="${i}">W${i}</option>`)}
function apply(){const y=+yearFilter.value,m=+monthFilter.value,w=+weekFilter.value,f=fromDate.value,t=toDate.value;render(ALL.filter(x=>{const d=parse(x["NBD"]);if(y&&(!d||d.getFullYear()!==y))return false;if(m&&(!d||d.getMonth()+1!==m))return false;if(w&&(!d||isoWeek(d)!==w))return false;if(f&&(!d||d<new Date(f+'T00:00:00')))return false;if(t&&(!d||d>new Date(t+'T23:59:59')))return false;return true}))}
function render(d){currentData=d;const total=d.length,o=d.filter(x=>x._gap!==null&&x._gap>0&&!has(x["Dispatched date"])).length,d3=d.filter(x=>!has(x["Dispatched date"])&&x._gap!==null&&x._gap<=0&&x._gap>=-3).length,d7=d.filter(x=>!has(x["Dispatched date"])&&x._gap!==null&&x._gap<=-4&&x._gap>=-7).length,dis=d.filter(x=>has(x["Dispatched date"])||txt(x["Overall status"]).toLowerCase()==='dispatched').length;set('totalCount',total);set('overdueCount',o);set('due3Count',d3);set('due7Count',d7);set('dispatchedCount',dis);set('totalPercent',total?'100%':'0%');set('overduePercent',pct(o,total));set('due3Percent',pct(d3,total));set('due7Percent',pct(d7,total));set('dispatchedPercent',pct(dis,total));pending(d);donut(d)}
function pending(d){const rows=d.filter(x=>!has(x["Dispatched date"])&&txt(x["Overall status"]).toLowerCase()!=='dispatched').sort((a,b)=>(b._gap??-999999)-(a._gap??-999999));set('pendingCount',rows.length+' items');pendingBody.innerHTML=rows.length?rows.map(x=>`<tr><td><span class="priority ${x._priority.cls}">${x._priority.text}</span></td><td>${txt(x["Project"])}<br><b>${txt(x["Build"])}</b></td><td>${txt(x["Machine/Equipment name"])}</td><td>${date(x["NBD"])}</td><td>${date(x["BFIH site arrive"])}</td><td class="${gapcls(x._gap)}">${x._gap===null?'':x._gap>0?'+'+x._gap:x._gap}</td><td class="stage">${x._stage}</td><td>${x._action}</td></tr>`).join(''):'<tr><td colspan="8" style="text-align:center;padding:30px;color:#64748b">No pending items</td></tr>'}
function donut(d){if(typeof Chart==='undefined')return;const c={};d.forEach(x=>{const s=has(x["Overall status"])?txt(x["Overall status"]):'No Status';c[s]=(c[s]||0)+1});if(statusChart)statusChart.destroy();statusChart=new Chart(statusChartCanvas=document.getElementById('statusChart'),{type:'doughnut',data:{labels:Object.keys(c),datasets:[{data:Object.values(c),backgroundColor:['#1769e0','#26a34a','#f58213','#ef2b1f','#eeb308','#94a3b8']}]},options:{responsive:true,maintainAspectRatio:false,cutout:'58%',plugins:{legend:{position:'bottom',labels:{boxWidth:10,font:{size:10}}}}}})}
function exportCSV(){const rows=currentData.map(x=>[x['Project'],x['Build'],x['Machine/Equipment name'],x['NBD'],x['BFIH site arrive'],x._gap,x._stage,x._action]);const csv=[["Project","Build","Machine","NBD","BFIH Site Arrive","CP Gap","Stage","Action"],...rows].map(r=>r.map(v=>'"'+txt(v).replaceAll('"','""')+'"').join(',')).join('
');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='SAE_dashboard_export.csv';a.click()}
function lang(l){langEn.classList.toggle('active',l==='en');langZh.classList.toggle('active',l==='zh');exportButton.textContent=l==='zh'?'导出':'Export';importButton.textContent=l==='zh'?'导入':'Import'}
function isoWeek(date){const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()));const day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()+4-day);const y=new Date(Date.UTC(d.getUTCFullYear(),0,1));return Math.ceil((((d-y)/86400000)+1)/7)}function parse(v){const s=txt(v);if(/^\d{4}-\d{2}-\d{2}$/.test(s)){const[y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)}if(/^\d{1,2}\/\d{1,2}\/\d{4}$/.test(s)){const[m,d,y]=s.split('/').map(Number);return new Date(y,m-1,d)}return null}function date(v){const d=parse(v);return d?`${String(d.getMonth()+1).padStart(2,'0')}/${String(d.getDate()).padStart(2,'0')}`:txt(v)}function has(v){const s=txt(v);return !!s&&s!=='-'&&s.toUpperCase()!=='TBC'}function txt(v){return v==null?'':String(v).trim()}function set(id,v){document.getElementById(id).textContent=v}function pct(n,t){return t?Math.round(n/t*100)+'%':'0%'}function gapcls(v){return v===null?'':v>0?'gap-overdue':v>=-7?'gap-near':'gap-safe'}