const assert=require('node:assert/strict');
const {mapRows}=require('./manufacture-source.js');
const headers=['Project','Phase','Type','Equipment','Spec','KO QTY','KO Date','CM NBD','CM Site','MFG status','Material Status','ACT ETD'];
const first=['TEST','EVT','NB','Test equipment','TEST-001',2,46235,46300,'SITE','','Material pending',''];
const rows=mapRows([headers,[null,null,null,null,8,13],first,[...first.slice(0,11),46260],[]]);
assert.equal(rows.length,2);
assert.equal(rows[0].Equipment,'Test equipment');
assert.equal(rows[0].Spec,'TEST-001');
assert.equal(rows[0].NBD,'2026-10-05');
assert.equal(rows[0]['Overall status'],'Material pending');
assert.equal(rows[1]['Overall status'],'Material pending','ACT ETD alone must not mark complete');
for(const status of ['Dispatched','dispatched','DISPATCHED','Completed - Dispatched to CM']){
 const row=first.slice();row[9]=status;
 assert.equal(mapRows([headers,row])[0]['Overall status'],'Dispatched');
}
const pending=first.slice();pending[9]='Assembly ongoing';
assert.equal(mapRows([headers,pending])[0]['Overall status'],'Assembly ongoing');
assert.throws(()=>mapRows([['Project']]),/columns missing/);
const updated=headers.filter(h=>h!=='Material Status').concat(['Remark','STD total Qty\nDRI: Test','STD Pending qty','OS/SM Pending qty\nDRI: Test','RM Status','CNC pending qty\nDRI: Test','Remark','Debug Start\n(Plan)\nDRI: Test','Debug Start\n(Plan)\nDRI: Test']);
const revised=updated.map(h=>({Project:'TEST',Phase:'EVT',Type:'NB',Equipment:'Test',Spec:'TEST-002','KO QTY':4,'CM NBD':46300,'MFG status':'CNC ongoing','STD total Qty\nDRI: Test':8,'STD Pending qty':0,'OS/SM Pending qty\nDRI: Test':3,'RM Status':1,'CNC pending qty\nDRI: Test':2}[h]??''));
revised[updated.indexOf('Remark')]='General note';revised[updated.lastIndexOf('Remark')]='Stage note';revised[revised.length-2]=46290;revised[revised.length-1]=46291;
const mapped=mapRows([updated,revised])[0];
assert.equal(mapped.Remark,'General note');
assert.match(mapped['STD Status'],/Pending: 0/);
assert.match(mapped['OS/SM Status'],/Pending: 3/);
assert.match(mapped['RM Status'],/100%/);
assert.match(mapped['CNC Status'],/Pending: 2/);
const debug=mapped._details.filter(d=>d.label.startsWith('Debug'));
assert.equal(debug.length,2);assert.notEqual(debug[0].column,debug[1].column);assert.notEqual(debug[0].value,debug[1].value);
console.log('Manufacture equipment and completion checks passed');
