const assert=require('node:assert/strict');
const {mapRows}=require('./manufacture-source.js');
const headers=['Project','Phase','Type','Spec','KO QTY','KO Date','CM NBD','CM Site','MFG status','Material Status','ACT ETD'];
const first=['TEST','EVT','NB','TEST-001',2,46235,46300,'SITE','','Material pending',''];
const rows=mapRows([headers,[null,null,null,8,13],first,[...first.slice(0,10),46260],[],[null,null,null,null,null,null,null,null,null,null,0]]);
assert.equal(rows.length,2);
assert.equal(rows[0]['Overall status'],'Material pending');
assert.equal(rows[1]['Overall status'],'Dispatched');
assert.equal(rows[0].NBD,'2026-10-05');
assert.equal(rows[0]['KO Date'],'2026-08-01');
assert.equal(rows[0].Spec,rows[1].Spec);
assert.throws(()=>mapRows([['Project']]),/columns missing/);
assert.equal(mapRows([headers,[...first.slice(0,10),'#REF!']])[0]['ACT ETD'],'');
console.log('Manufacture mapping checks passed');
